version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    entrypoint: sleep infinity
    environment:
      - POLLS_DEBUG=1
      - POLLS_HOST=0.0.0.0
      - POLLS_PORT=5000
      - POLLS_DB_HOST=postgres
      - POLLS_DB_USER=polls
      - POLLS_DB_PASSWORD=password
      - POLLS_DB_NAME=polls
    ports:
      - 5000
    volumes:
      - ./:/code/

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=polls
      - POSTGRES_DB=polls
    volumes:
        - ./data/:/var/lib/postgresql/data

  wait_postgres:
    image: "waisbrot/wait"
    environment:
      TARGETS: postgres:5432

  migrate:
    build: migrate/
    entrypoint: sleep 10000d
    volumes:
      - ./migrate/:/migrations/
    environment:
      - DB_HOST=postgres
      - DB_USER=polls
      - DB_PASSWORD=password
      - DB_NAME=polls

  postgres-test:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=polls-test
      - POSTGRES_DB=polls-test
    volumes:
        - ./data-test/:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
