FROM python:3.6.4-stretch

RUN pip install -U pip

RUN mkdir -p /code/
WORKDIR /code/

COPY ./demo_polls/ /code/demo_polls/
COPY ./setup.py /code/
COPY ./requirements.txt /code/
COPY ./requirements-dev.txt /code/

RUN pip install -e .
RUN pip install -r requirements-dev.txt

RUN cd /usr/local/bin/ && \
  curl -L -s https://github.com/mattes/migrate/releases/download/v3.0.1/migrate.linux-amd64.tar.gz | tar xz && \
  mv migrate.linux-amd64 migrate

RUN cd /usr/local/bin/ && \
  curl -L -s https://github.com/go-task/task/releases/download/v2.0.0/task_linux_amd64.tar.gz | tar xz

ENV POLLS_DEBUG=0
ENV POLLS_HOST=0.0.0.0
ENV POLLS_PORT=5000

ENV POLLS_DB_HOST=postgres
ENV POLLS_DB_USER=polls
ENV POLLS_DB_PASSWORD=password
ENV POLLS_DB_NAME=polls

ENTRYPOINT ["/usr/local/bin/polls"]
CMD ["--help"]
